{
  "name": "ci",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": {
      "branches": [
        "master"
      ]
    },
    "workflow_dispatch": {}
  },
  "jobs": {
    "build": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "setup emacs",
          "uses": "purcell/setup-emacs@master",
          "with": {
            "version": "24.1"
          }
        },
        {
          "name": "install eldev",
          "run": "curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh"
        },
        {
          "name": "lint",
          "run": "eldev lint"
        }
      ]
    }
  }
}
